### ISSUE TITLE
fail to compile with gcc-4.7.1 using "-Wall -Werror"

### ISSUE THREAD

**Issue by ofree** [troglobit/pimd#16]
if remove "-Wall -Werror", then works fine!
not sure whether should fix the code or the compiler,
thanks.

main.c: In function ‘main’:
main.c:490:5: error: signed and unsigned type in conditional expression [-Werror=sign-compare]
main.c:490:5: error: signed and unsigned type in conditional expression [-Werror=sign-compare]
main.c:493:2: error: signed and unsigned type in conditional expression [-Werror=sign-compare]
main.c:493:2: error: signed and unsigned type in conditional expression [-Werror=sign-compare]
main.c:583:3: error: signed and unsigned type in conditional expression [-Werror=sign-compare]
main.c:583:3: error: signed and unsigned type in conditional expression [-Werror=sign-compare]
main.c:586:7: error: signed and unsigned type in conditional expression [-Werror=sign-compare]
main.c:586:7: error: signed and unsigned type in conditional expression [-Werror=sign-compare]
main.c:613:7: error: signed and unsigned type in conditional expression [-Werror=sign-compare]
main.c:613:7: error: signed and unsigned type in conditional expression [-Werror=sign-compare]
cc1: all warnings being treated as errors
make: **\* [main.o] Error 1
make: INTERNAL: Exiting with 8 jobserver tokens available; should be 7!
- ERROR: net-misc/pimd-9999 failed (compile phase):
-   emake failed
- 
- If you need support, post the output of `emerge --info '=net-misc/pimd-9999'`,
- the complete build log and the output of `emerge -pqv '=net-misc/pimd-9999'`.
- This ebuild is from an overlay named 'ofree': '/var/lib/layman/ofree/'
- The complete build log is located at '/var/build/portage/net-misc/pimd-9999/temp/build.log'.
- The ebuild environment file is located at '/var/build/portage/net-misc/pimd-9999/temp/environment'.
